name: "Run cargo-msrv"
on:
  workflow_dispatch:
  push:
    paths: ["**/Cargo.toml", "**/Cargo.lock"]
    branches: ["**"]
    
jobs:
  cargo-msrv:
    permissions:
      contents: write
      pull-requests: write
    uses: iiiii7d/cargo-msrv-workflow/.github/workflows/workflow.yml@26d4b3e0cf218038d4f6ab333e0e9bc5db75a0ea # main
